import React from "react";
import Head from "next/dist/shared/lib/head";
import Script from "next/script";
import { useRouter } from "next/router";
import { Hydrate, QueryClient, QueryClientProvider } from "react-query";
import Layout from "../components/common/Layout";
import "../styles/globals.css";
function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const { category } = router.query;
  const queryClient = React.useRef(new QueryClient());
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="manifest.json" />
        <title>Hacker News{category ? ` | ${category[0]}` : null}</title>
        <script type="module">
          import 'https//cdn.jsdelivr.net/npm/@pwabuilder/pwaupdate'; const el =
          document.createElement('pwa-update'); document.body.appendChild(el);
        </script>
      </Head>
      <Script></Script>
      <QueryClientProvider client={queryClient.current}>
        <Hydrate state={pageProps.dehydratedState}>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </Hydrate>
      </QueryClientProvider>
    </>
  );
}
export default MyApp;
